"""The dashboard Phase-1 JSON must be a pure derivation of the corrected archives.

The committed dashboard/public/data/phase1.json is regenerated by
dashboard/scripts/prepare_data.py --only phase1 from phase1_v2_corrected/ files
only. These tests pin that contract: byte-identical output and no withdrawn
protocol-v1 schema keys.
"""
import importlib.util
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
COMMITTED = ROOT / "dashboard" / "public" / "data" / "phase1.json"


def _load_builder():
    spec = importlib.util.spec_from_file_location(
        "prepare_data", ROOT / "dashboard" / "scripts" / "prepare_data.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_build_phase1_is_byte_identical_to_committed_file(tmp_path):
    module = _load_builder()
    module.build_phase1(out_dir=tmp_path)
    assert (tmp_path / "phase1.json").read_bytes() == COMMITTED.read_bytes()


def test_build_phase1_has_no_withdrawn_schema(tmp_path):
    module = _load_builder()
    module.build_phase1(out_dir=tmp_path)
    data = json.loads((tmp_path / "phase1.json").read_text(encoding="utf-8"))
    assert "registered_pooled20" not in data
    assert data["protocol_version"] == "phase1-v2"
    assert len(data["registered_family"]) == 5
    for row in data["registered_family"]:
        assert row["p"] > 0.0
        assert row["q"] > 0.0
